services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - app_db:/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  app_db:
